name: Setup Linux dependencies
description: Install host dependencies for building QuackCraft Launcher

runs:
  using: composite

  steps:
    - name: Install host dependencies
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y install \
          dpkg-dev \
          ninja-build extra-cmake-modules pkg-config \
          libxcb-cursor-dev
